print("Caixa:")

print("********")
print("*      *")
print("*      *")
print("*      *")
print("********")
        
print("\nseta:")
print("*")
print("**")
print("***")
print("****")
print("***")
print("**")
print("*")

print("\nOval:")
print("          *")
print("    *************")
print("  *****************")
print(" *******************")
print(" *******************")
print("*********************")
print(" *******************")
print(" *******************")
print("  *****************")
print("    *************")
print("          *")


print("\nLosango:")
print("    *")
print("   ***")
print("  *****")
print(" *******")
print("  *****")
print("   ***")
print("    *")